config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  registrations: 'users/registrations'
}
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :items do
    resources :likes, only: [:create, :destroy]
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    resources :images, only: [:new, :create]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :users, only: [:new, :show]
  resources :cards, only: [:new, :create, :show, :destroy] do
  end
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :category
  belongs_to :user
  has_many :images, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  accepts_nested_attributes_for :images, allow_destroy: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :period

  enum delivery_cost:{"送料込み（出品者負担）": 1, "着払い（購入者負担）": 2}

  [:name, :explanation, :quality, :delivery_cost, :prefecture_id, :period_id, :price, :user_id, :images, :category_id].each do |v|
    validates v, presence: true
  end
  validates :name, length: { maximum: 50 }
  validates :price, :numericality => { greater_than_or_equal_to: 50, less_than: 1000000 }
 
  def self.search(search)
    if search
      Item.where('name LIKE(?)', "%#{search}%").order("created_at DESC")
    else
      Item.all.order("created_at DESC")
    end
  end
end

app/controllers/items/searches_controller.rb
class Items::SearchesController < ApplicationController
  before_action :set_search
  def index
    @items = @search.result(distinct: true)
    @keyword = (search_params[:name_cont])
  end

  private
  def set_search
    # 検索オブジェクト
    @search = Item.ransack(params[:q])
  end

  def search_params
    params.require(:q).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search, :get_category_children, :get_category_grandchildren]
  def index
    @items_new = Item.all.order("created_at DESC")
    @items_archive = Item.all
    @items_random = Item.order("RAND()").limit(8)
  end

  def new
    @item = Item.new
    @image = @item.images.build
    #親階層のカテゴリー取得
    @category_parent_array = Category.where(ancestry: nil)
  end

  # 子階層のカテゴリー取得
  def get_category_children
      #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
      @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
  end

  # 孫階層のカテゴリー取得
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash.now[:notice] = "出品しました！"
      redirect_to item_path(@item.id)
    else
      @image = @item.images.build
      @category_parent_array = Category.where(ancestry: nil)
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
    @like = Like.new
  end

  def search
    @items = Item.search(params[:keyword])
    @keyword = params[:keyword]
  end

  def edit
    @category_grandchildren = @item.category
    @category_grandchildren_array = @category_grandchildren.siblings
    @category_children = @category_grandchildren.parent
    @category_children_array = @category_children.siblings
    @category_parent = @category_grandchildren.root
    @category_parent_array = @category_parent.siblings
  end

  def update
      @category_grandchildren = @item.category
      @category_grandchildren_array = @category_grandchildren.siblings
      @category_children = @category_grandchildren.parent
      @category_children_array = @category_children.siblings
      @category_parent = @category_grandchildren.root
      @category_parent_array = @category_parent.siblings
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to user_path
    else
      render :show
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :quality, :delivery_cost, :period_id, :price,  :prefecture_id, :category_id,images_attributes: [:image, :item_id, :_destroy, :id] ).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_with model: @item, class:"Form__container", local: true do |f|
  .Form__group
    .Form__label
      = f.label :image, "出品画像"
      %span.Form__label--required 必須
    .Form__field
      %p.img__upload__comment ※最大10枚までアップロード可
      #image-box
        #previews
          - if @item.persisted?
            - @item.images.each_with_index do |image, i|
              .previewsBox{data: { index: i }}
                .previewsBox__image
                  = image_tag image.image.url, data: { index: i }
                .js-remove.text-center
                  削除
        = f.fields_for :images do |image|
          .js-file_group{"data-index" => "#{image.index}"}
            - if @item.persisted?
              = image.file_field :image, class: 'js-file',style: "display: none;"
            - else
              = image.file_field :image, class: 'js-file'
          - if @item.persisted?
            = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
        - if @item.persisted?
          - if @item.images.count <= 9
            .js-file_group{"data-index" => "#{@item.images.count}"}
              = file_field_tag :image, name: "item[images_attributes][#{@item.images.count}][image]", class: 'js-file'
    .Form__error
      - if @item.errors.include?(:images)
        %p{:style => "color: red;"}
          = @item.errors.full_messages_for(:images).first
  .Form__group
    .Form__label
      = f.label :name, "商品名"
      %span.Form__label--required 必須
    .Form__field
      = f.text_field :name, placeholder: "全角20文字まで", class: "Form__input", maxlength: "40"
    .Form__error
      - if @item.errors.include?(:name)
        %p{:style => "color: red;"}
          = @item.errors.full_messages_for(:name).first
  .Form__group
    .Form__label
      = f.label :explanation, "商品説明"
      %span.Form__label--required 必須
    .Form__field
      = f.text_area :explanation, class: "Form__input", placeholder: "例）2019年ごろに1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
    .Form__error
      - if @item.errors.include?(:explanation)
        %p{:style => "color: red;"}
          = @item.errors.full_messages_for(:explanation).first
  .Form__group
    .Form__label
      = f.label :category, "カテゴリー"
      %span.Form__label--required 必須
    - if @item.persisted?
      .Form__field.categoryList
        = f.collection_select :category_id, @category_parent_array, :id, :name, { include_blank: '選択してください', selected: @category_parent.id}, { class: "Form__input", id: 'parent_category'}
        = f.collection_select :category_id, @category_children_array, :id, :name, { include_blank: '選択してください', selected: @category_children.id}, { class: "Form__input", id: 'children_category'}
        = f.collection_select :category_id, @category_grandchildren_array, :id, :name, { include_blank: '選択してください'}, { class: "Form__input", id: 'grandchildren_category'}
    - else
      .Form__field.categoryList
        = f.collection_select :category_id, @category_parent_array, :id, :name, { include_blank: '選択してください'}, { class: "Form__input", id: 'parent_category'}
    .Form__error
      - if @item.errors.include?(:category)
        %p{:style => "color: red;"}
          = @item.errors.full_messages_for(:category).first
  .Form__group
    .Form__label
      = f.label :quality, "商品の状態"
      %span.Form__label--required 必須
    .Form__field
      = f.select :quality,['新品、未使用', '未使用に近い', '目立った傷や汚れなし', 'やや傷や汚れあり','傷や汚れあり', '全体的に状態が悪い'],  { include_blank: '選択してください' }, { class: "Form__input", id: "quality_id" }
    .Form__error
      - if @item.errors.include?(:quality)
        %p{:style => "color: red;"}
          = @item.errors.full_messages_for(:quality).first
  .Form__group
    .Form__label
      = f.label :delivery_cost,"配送料の負担"
      %span.Form__label--required 必須
    .Form__field
      = f.select :delivery_cost, Item.delivery_costs.keys, {include_blank: '選択してください'},{class: "Form__input"}
    .Form__error
      - if @item.errors.include?(:delivery_cost)
        %p{:style => "color: red;"}
          = @item.errors.full_messages_for(:delivery_cost).first
  .Form__group
    .Form__label
      = f.label "発送元の地域"
      %span.Form__label--required 必須
    .Form__field
      = f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {include_blank: '選択してください'},{class: "Form__input"})
    .Form__error
      - if @item.errors.include?(:prefecture_id)
        %p{:style => "color: red;"}
          = @item.errors.full_messages_for(:prefecture_id).first
  .Form__group
    .Form__label
      = f.label :period, "発送までの日数"
      %span.Form__label--required 必須
    .Form__field
      = f.collection_select(:period_id, Period.all, :id, :integer, {include_blank: '選択してください'},{class: "Form__input"})
    .Form__error
      - if @item.errors.include?(:period_id)
        %p{:style => "color: red;"}
          = @item.errors.full_messages_for(:period_id).first
  .Form__group
    .Form__label
      = f.label :price, "販売価格"
      %span.Form__label--required 必須
    .Form-price
      %span.price-left ￥
      .Form__field
        = f.number_field :price, class: "Form__input", placeholder:"0"
    .Form__error
      - if @item.errors.include?(:price)
        %p{:style => "color: red;"}
          = @item.errors.full_messages_for(:price).first
  .Form__group--last
    .Form__btn.Form__btn--margin
      = f.submit class:"Form__exhibitBtn"

app/views/items/_like.html.haml
%ul
  %li
    .like-function__like
      = link_to item_likes_path(@item.id), class:"likebtn", method: :post, remote: true do
        %i.fa.fa-star
        いいね件数:
        =@item.likes.count

app/views/items/_liked.html.haml
%ul
  %li
    .like-function__unlike
      = link_to item_like_path(@item.id), class:"unlikebtn", method: :delete, remote: true do
        %i.fa.fa-star
        いいね件数
        =@item.likes.count

app/views/items/destroy.html.haml
.destroymain
  .destroycontents
    %h4.destroysuccess
      削除されました
    .destroybtn
      =link_to "商品一覧へ戻る",items_path

app/views/items/edit.html.haml
.NewMain
  .Form
    = render partial: 'form'

app/views/items/index.html.haml
.main
  / アプリ紹介
  .mainApps
    .appsContents
      %h2.appsContents__subtitle
        人生を変えるフリマアプリ
      %p.appsContents__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .appsContents__btn
        = link_to "https://www.apple.com/jp/", class: "appsContents__btn--apple" do
          = image_tag "Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg",alt: "appleicon"
        = link_to "https://play.google.com/store", class: "appsContents__btn--google" do
          = image_tag "google-play-badge.png" ,alt: "gogleicon"

  / 理由
  .mainReasons
    %h2.subtitle
      FURIMAが選ばれる3つの理由
      .subtitle__border
    %ul.reasonsLists
      %li.reasonsList
        .reasonsList__image
          %span.number 1
          = image_tag "pict/pict-reason-01.jpg"
        .reasonsList__text
          %span 3分
          ですぐに出品
        .reasonsList__description
          スマホで入力するだけで簡単に出品できる！
      %li.reasonsList
        .reasonsList__image
          %span.number 2
          = image_tag "pict/pict-reason-02.jpg"
        .reasonsList__text
          %span シンプル
          で使いやすい
        .reasonsList__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.reasonsList.reasonsList--last
        .reasonsList__image
          %span.number 3
          = image_tag "pict/pict-reason-03.jpg"
        .reasonsList__text
          %span 手数料
          業界最安
        .reasonsList__description
          最大3%でお得に出品&購入！


  / アピール

  .mainAppeal
    .appadsContents
      %h2.appadsContents__topic.appadsContents--shadow
        会員数日本一位
      %p.appadsContents__text.appadsContents--shadow
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .appadsContents__btn
        = link_to "https://www.apple.com/jp/", class: "appadsContents__btn--apple" do
          = image_tag "Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg",alt:"appleicon"
        = link_to "https://play.google.com/store", class: "appadsContents__btn--google" do
          = image_tag "google-play-badge.png" ,alt:"gogleicon"

  / 特徴
  .mainFeatures
    %h2.subtitle
      FURIMAの特徴
      .subtitle__border
    %ul.featuresLists
      %li.featuresList
        .featuresList__image
          = image_tag "icon/icon-01.png"
        .featuresList__text
          簡単に売り買いできる
        .featuresList__description
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.featuresList
        .featuresList__image
          = image_tag "icon/icon-03.png"
        .featuresList__text
          売上金は即日振込みに対応
        .featuresList__description
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.featuresList.featuresList--last
        .featuresList__image
          = image_tag "icon/icon-04.png"
        .featuresList__text
          様々な支払いに対応
        .featuresList__description
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。



  .mainProducts
    %h2.mainProducts__head
      ピックアップカテゴリー
    .productsBox
      .boxhead
        =link_to search_items_path, keyword: nil  do
          %h3.head__title
            新規投稿商品
      .boxlists
        - @items_new.first(4).each do |item|
          .boxlist
            =link_to item_path(item.id) do
              %figure.listimage
                = image_tag item.images.first.image.url
                - if item.purchaser_id.present?
                  .items-box-sold
                    .items-box-sold__inner SOLD
              .listbody
                %h3.name
                  = item.name
                .datails
                  %ul
                    %li
                      = item.price
                    %li
                      %i.fas.fa-star
                        =item.likes.count
                  %p
                    (税込)
  .mainProducts
    %h2.mainProducts__head
      商品一覧
    .productsBox
      .itemsMore
        = link_to search_items_path do
          もっと見る
          %i.fa.fa-angle-right
      .boxlists
        - @items_random.each do |item|
          .boxlist
            =link_to item_path(item.id) do
              %figure.listimage
                = image_tag item.images.first.image.url
                - if item.purchaser_id.present?
                  .items-box-sold
                    .items-box-sold__inner SOLD
              .listbody
                %h3.name
                  = item.name
                .datails
                  %ul
                    %li
                      = item.price
                    %li
                      %i.fas.fa-star
                        0
                  %p
                    (税込)

app/views/items/new.html.haml
.NewMain
  .Form
    = render partial: 'form'

app/views/items/search.html.haml
.mainProducts
  %h2.mainProducts__head
    -if @keyword.blank?
      商品一覧
    - else
      = "#{@keyword}の検索結果"
  .productsBox
    .boxlists
      - @items.each do |item|
        .boxlist
          =link_to item_path(item) do
            %figure.listimage
              = image_tag item.images.first.image.url, size: "220x150"
              - if item.purchaser_id.present?
                .items-box-sold
                  .items-box-sold__inner SOLD
            .listbody
              %h3.name
                = item.name
              .datails
                %ul
                  %li
                    = item.price
                  %li
                    %i.fas.fa-star
                      0
                %p
                  (税込)

app/views/items/show.html.haml
.main
  .showMain
    .showcontent
      .topcontent
        .itembox
          %h2.itembox__name
            = @item.name
          .itembox__top
            %ul
              %li
                %figure.listimage
                  - if @item.purchaser_id.present?
                    .items-box-sold
                      .items-box-sold__inner SOLD
                %ul.firstimage
                  %li.firstimage__big
                    = image_tag @item.images.first.image.url
                  %ul.subimage
                    - @item.images.each do |image|
                      %li.subimage__small
                        = image_tag image.image.url
          .itembox__price
            %span
              ¥
              %span<>
              =@item.price
            .itembox__tax
              %h2
                (税込)
              %h2
                送料込み
          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td
                    = @item.user.nickname
                %tr
                  %th カテゴリー
                  %td
                    %br
                      = @item.category.root.name
                    %br
                      = @item.category.parent.name
                    %br
                      = @item.category.name
                %tr
                  %th 商品の状態
                  %td
                    = @item.quality
                %tr
                  %th 配送料の負担
                  %td
                    = @item.delivery_cost
                %tr
                  %th 発送元の地域
                  %td
                    = @item.prefecture.name
                %tr
                  %th 発送日の目安
                  %td
                    = @item.period.integer
                %tr
                  %th 商品説明
                  %td
                    = @item.explanation

          .morelist
            - if user_signed_in?
              - if current_user.id == @item.user_id
                .morelist__editbtn
                  =link_to edit_item_path(@item.id), method: :get do
                    編集
                .morelist__deletebtn
                  =link_to item_path(@item.id), method: :delete do
                    削除
              -elsif @item.purchaser_id.present?
                .morelist__soldbtn
                  売り切れました
              -else
                .morelist__deletebtn
                  =link_to  item_purchase_index_path(@item.id) do
                    購入画面に進む
            - else
              .morelist__deletebtn
                = link_to new_user_session_path do
                  購入画面に進む

          .option
            %ul
              %li
                -if user_signed_in? && current_user.already_liked?(@item)
                  = button_to item_like_path(@item), class:"likebtn", method: :delete do
                    %i.fa.fa-star
                    いいね件数:
                    =@item.likes.count
                -else
                  = button_to item_likes_path(@item), class:"likebtn" do
                    %i.fa.fa-star
                    いいね件数:
                    =@item.likes.count


            %ul.report
              %li.reportbtn
                =link_to "#" do
                  %i.fa.fa-flag
                    不適切の商品の通報
          .topbtn
            = link_to items_path do
              %h2.topbtn__text
              トップページに戻る
          .commentbox
            .commentbox__input
              -if user_signed_in?
                %ul
                  =form_with model:[@item, @comment],class:"commentform", local: true, id: "new_comment" do |f|
                    %li
                      =f.text_area :text, class: "textbox"
                    %li
                      =f.submit "コメントする", class:"commentbtn"
              -else
                %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
            .commentbox__show
              .commentbox__show--box
                -if @comments
                  .commentindex
                    %h4 コメント一覧
                  -@comments.each do |comment|
                    .commentcontent
                      .commentuser
                        =link_to "/users/#{comment.user_id}" do
                          =comment.user.nickname
                      .commenttext
                        =comment.text
                      .commenttime
                        =comment.created_at.strftime("%Y年%m月%d日 %H時%M分")

app/views/items/update.html.haml
.editmain
  .editcontents
    %h4.editsuccess
      編集されました
    .editbtn
      =link_to "商品一覧へ戻る",items_path