config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  registrations: 'users/registrations'
}
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :items do
    resources :likes, only: [:create, :destroy]
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    resources :images, only: [:new, :create]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :users, only: [:new, :show]
  resources :cards, only: [:new, :create, :show, :destroy] do
  end
  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"

  def new
     # cardがすでに登録済みの場合、indexのページに戻します。
     @card = Card.where(user_id: current_user.id).first
     redirect_to action: "show" if @card.present?   
  end

  def create
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjpToken'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        email: current_user.email, #なくてもOK
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show", notice:"支払い情報の登録が完了しました"
      else
        redirect_to action: "new"
      end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      redirect_to action: "index", alert: "削除できませんでした"
    end
  end

  def buy
    @item = Item.find(params[:item_id])
    # すでに購入されていないか？
    if @item.buyer.present? 
      redirect_back(fallback_location: root_path) 
    elsif @card.blank?
      # カード情報がなければ、買えないから戻す
      redirect_to action: "new"
      flash[:alert] = '購入にはクレジットカード登録が必要です'
    else
      # 購入者もいないし、クレジットカードもあるし、決済処理に移行
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      # 請求を発行
      Payjp::Charge.create(
      amount: @item.price,
      customer: @card.customer_id,
      currency: 'jpy',
      )
      # 売り切れなので、productの情報をアップデートして売り切れにします。
      if @item.update(buyer_id: current_user.id)
        flash[:notice] = '購入しました。'
        redirect_to controller: 'products', action: 'show', id: @item.id
      else
        flash[:alert] = '購入に失敗しました。'
        redirect_to controller: 'products', action: 'show', id: @item.id
      end
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card, only: [:show, :destroy]
  def index

  end

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to card_path(current_user.id) if card.present?
  end

  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

    if params['payjp-token'].blank?
      redirect_to action: :new, alert: "あいうあ言うあいうあ"
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params['payjp-token'],
      )
      @card = Card.new(user: current_user, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_back_or card_path(current_user.id)
      else
        redirect_to action: :new, alert: "クレジットカードを登録できませんでした。"
      end
    end
  end

  def show
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def destroy
    if @card.blank?
      redirect_to action: "show"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to action: "new"
  end
  private
  def set_card
    @card = Card.where(user_id: current_user.id).first
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
.creditcard
  %h2.title クレジットカード登録
  = form_with url: cards_path, method: :post, html: { name: "inputForm" }, class: "cardform" do |f|
    = f.label :カード番号, class: 'label'
    %span.necessary 必須
    %br/
    = f.text_field :card_number, type: 'text', class: 'input-number', placeholder: '半角数字のみ', maxlength: "16", id: "card_number"
    %br/
    = f.label :有効期限, class: 'label'
    %span.necessary 必須
    %br/
    .expire
      .expiretime
        = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'input-expire'
        %span.expire-month 月
        %br
      .expiretime
        = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'input-expire'
        %span.expire-year 年
    = f.label :セキュリティコード, class: 'label'
    %span.necessary 必須
    %br/
    = f.text_field :cvc, type: 'text', class: 'input-number', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4", id: "cvc"
    %br/
    #card_token
    = f.submit '追加する', class: 'creditcardbtn', id: 'token_submit'

app/views/cards/show.html.haml
.cardinfo
  .cardinfo-contents
    %h2.card-title 
      =current_user.last_name
      %span
      様の登録クレジットカード情報
    %br
    .card-info
      .card-info__name
        %p カード番号   :  
      .card-info__number
        = "**** **** **** " + @default_card_information.last4
    %br
  .card-date
    .card-date__name
    %p 有効期限  :  
    .card-date__date
      - exp_month = @default_card_information.exp_month.to_s
      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
      = exp_month + " / " + exp_year
= form_tag(card_path, method: :delete, id: 'charge-form',  name: "inputForm", class: "delete-submit") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button.card-deletebtn 削除する