config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks',
  registrations: 'users/registrations'
}
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :items do
    resources :likes, only: [:create, :destroy]
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    resources :images, only: [:new, :create]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :users, only: [:new, :show]
  resources :cards, only: [:new, :create, :show, :destroy] do
  end
  
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  belongs_to :user, optional: true

  # 携帯番号（ハイフンなし10桁or11桁）
  validates :phone_number, presence: true ,uniqueness: true,
            format: { with: /\A\d{10,11}\z/ }
  validates :postal_code, presence: true,
            # 郵便番号(ハイフンあり7桁)
            format: { with: /\A\d{3}-\d{4}\z/, message: "is must NOT contain any other characters than alphanumerics." }
  [:prefecture_id, :city, :house_number].each do |v|
    validates v, presence: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :text, length: { maximum: 200 }
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item
  mount_uploader :image, ImageUploader
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :category
  belongs_to :user
  has_many :images, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  accepts_nested_attributes_for :images, allow_destroy: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :period

  enum delivery_cost:{"送料込み（出品者負担）": 1, "着払い（購入者負担）": 2}

  [:name, :explanation, :quality, :delivery_cost, :prefecture_id, :period_id, :price, :user_id, :images, :category_id].each do |v|
    validates v, presence: true
  end
  validates :name, length: { maximum: 50 }
  validates :price, :numericality => { greater_than_or_equal_to: 50, less_than: 1000000 }
 
  def self.search(search)
    if search
      Item.where('name LIKE(?)', "%#{search}%").order("created_at DESC")
    else
      Item.all.order("created_at DESC")
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/period.rb
class Period < ActiveHash::Base

  self.data = [
    {id: 1, integer: '1〜2日で発送'}, {id: 2, integer: '2〜3日で発送'},{id: 3, integer: '4〜7日で発送'}
  ]
  include ActiveHash::Associations
  has_many :items

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]

  include ActiveHash::Associations
  has_many :items
  has_many :address

end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :items
  has_one :address
  has_many :comments
  has_one :card, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :item
  has_many :sns_credentials

  def already_liked?(item)
    self.likes.exists?(item_id: item.id)
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  enum gender: { "男性": 1, "女性": 2}
  validates :password, length: { minimum: 7 }
  validates :nickname, presence: true, uniqueness: true
  # 全角ひらがな、全角カタカナ、漢字
  VALID_NAME_REGEX = /\A[ぁ-んァ-ン一-龥]/
  [:last_name, :first_name].each do |v|
    validates v, format: { with: VALID_NAME_REGEX }
  end
  #　全角ひらがな
  VALID_NAME_READ_REGEX = /\A[ぁ-んー－]+\z/
  [:last_name_read, :first_name_read].each do |v|
    validates v, format: { with: VALID_NAME_READ_REGEX }
  end

  [:nickname, :last_name, :first_name, :last_name_read, :first_name_read, :birthday, :email ,:password].each do |v|
    validates v, presence: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_btn.html.haml
-if user_signed_in? && !request.path.include?("items/new")
  = link_to new_item_path do
    .ExhibitBtn
      .ExhibitBtn__text
        出品する
      = image_tag "icon/icon_camera.png" 

app/views/layouts/_footer.html.haml
/ バナー
.mainBanner
  .bannerContents
    %h2.bannerContents__topic.bannerContents--shadow
      だれでもかんたん、人生を変えるフリマアプリ
    %p.bannerContents__text.bannerContents--shadow
      今すぐ無料ダウンロード
    .bannerContents__btn
      = link_to "https://www.apple.com/jp/", class: "bannerContents__btn--apple" do
        = image_tag "Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg",alt:"appleicon"
      = link_to "https://play.google.com/store", class: "bannerContents__btn--google" do
        = image_tag "google-play-badge.png" ,alt:"gogleicon"


/ フッター
%footer.footer
  %ul.footer__contents
    %li.footer__list
      %h2.list__title
        FURIMAについて
      %ul
        %li
          =link_to "会社概要（運営会社）", "#" 
        %li
          =link_to "プライバシーポリシー", "#"
        %li
          =link_to "FURIMA利用規約","#"
        %li
          =link_to "ポイントに関する特約","#"
    %li.footer__list
      %h2.list__title
        FURIMAを見る
      %ul
        %li
          =link_to "カテゴリー一覧", "#"
        %li
          =link_to "ブランド一覧", "#"
    %li.footer__list
      %h2.list__title
        ヘルプ＆ガイド
      %ul
        %li
          =link_to "FURIMAガイド", "#"
        %li
          =link_to "FURIMAロゴ利用ガイドライン", "#" 
        %li
          =link_to "お知らせ", "#" 
  .footer__logo
    =link_to root_path do
      = image_tag "logo/logo-white.png",alt:"logo"
  %p
    ©　FURIMA

app/views/layouts/_header.html.haml
%header.header
  .headerInner
    .headerMain
      .headerMain__icon
        =link_to root_path do
          =image_tag "logo.png",alt:"アイコン"
      .searchBox
        = form_with(url: search_items_path, local: true, method: :get, class: "searchBox__form") do |f|
          = f.text_field :keyword, placeholder: "キーワードから探す", class: "searchBox__input"
          = button_tag type: 'submit' do
            = image_tag 'icon/icon-search 1.png', alt: '検索アイコン'
    .nav
      .navLeft
        .navLeft__item#category_tree
          = link_to "カテゴリー", "#"
          / カテゴリー覧html
          .tree.tree__parent.displayNone
            %ul.categoryTree
              - @category_parent_array.each do |parent| 
                = link_to "#", class: "categoryTreeParent categoryTree__parent categoryTree__item" do
                  %li.categoryTree__item--name{data: { index: "#{parent.id}" }}
                    = parent.name
        .navLeft__item#brand
          = link_to "ブランド", "#"
          .tree.displayNone
            %ul.categoryTree
              %li.categoryTree__item
                = link_to "アイテム1", "#"
              %li.categoryTree__item
                = link_to "アイテム2", "#"
              %li.categoryTree__item
                = link_to "アイテム3", "#"
              %li.categoryTree__item
                = link_to "アイテム4", "#"
              %li.categoryTree__item
                = link_to "アイテム5", "#"
              %li.categoryTree__item
                = link_to "アイテム6", "#"
      .navRight
        -if user_signed_in?
          .navRight__item
            = link_to "ログアウト", destroy_user_session_path, method: :DELETE
          .navRight__item
            = link_to "マイページ", user_path(current_user.id)
        -else
          .navRight__item
            = link_to "ログイン", new_user_session_path
          .navRight__item
            = link_to "新規会員登録", new_user_path

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample79d
    = csrf_meta_tags
    = csp_meta_tag
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  %body
    = render partial: "layouts/header"
    = render 'layouts/notifications'
    = yield
    = render partial: "layouts/btn"
    = render partial: "layouts/footer"